name: CI on multi-event

on:
  push:
    branches:
      - main
      - dev
  pull-request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo basic info"
        run: |
          echo "REF : $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action : $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
